INSERT INTO category (description) VALUES ('American');
INSERT INTO category (description) VALUES ('Italian');
INSERT INTO category (description) VALUES ('Mexican');
INSERT INTO category (description) VALUES ('Fast Food');
INSERT INTO unit_measure (measure) VALUES ('Teaspoon');
INSERT INTO unit_measure (measure) VALUES ('Tablespoon');
INSERT INTO unit_measure (measure) VALUES ('Cup');
INSERT INTO unit_measure (measure) VALUES ('Pinch');
INSERT INTO unit_measure (measure) VALUES ('Ounce');
INSERT INTO unit_measure (measure) VALUES ('Each');
INSERT INTO unit_measure (measure) VALUES ('Dash');
INSERT INTO unit_measure (measure) VALUES ('Pint');
